export const initialData = [
  {
    Source: "Meta",
    Amount: 846.0,
    Status: "Active",
    UserId: 7623,
    Joined: "October",
    Group: "Finance",
  },
  {
    Source: "App XYZ",
    Amount: 125.5,
    Status: "Pending",
    UserId: 5632,
    Joined: "November",
    Group: "Tech",
  },
  {
    Source: "App ABC",
    Amount: 320.0,
    Status: "Cancelled",
    UserId: 9876,
    Joined: "September",
    Group: "Finance",
  },
  // Add more rows here
  {
    Source: "App 1",
    Amount: 200.0,
    Status: "Active",
    UserId: 1234,
    Joined: "January",
    Group: "Marketing",
  },
  {
    Source: "App 2",
    Amount: 150.0,
    Status: "Pending",
    UserId: 5678,
    Joined: "February",
    Group: "Tech",
  },
  {
    Source: "App 3",
    Amount: 75.0,
    Status: "Active",
    UserId: 9012,
    Joined: "March",
    Group: "Finance",
  },
  {
    Source: "App 4",
    Amount: 500.0,
    Status: "Cancelled",
    UserId: 3456,
    Joined: "April",
    Group: "Marketing",
  },
  {
    Source: "App 5",
    Amount: 300.0,
    Status: "Active",
    UserId: 7890,
    Joined: "May",
    Group: "Tech",
  },
  {
    Source: "App 6",
    Amount: 100.0,
    Status: "Pending",
    UserId: 2345,
    Joined: "June",
    Group: "Finance",
  },
  {
    Source: "App 7",
    Amount: 250.0,
    Status: "Cancelled",
    UserId: 6789,
    Joined: "July",
    Group: "Marketing",
  },
  {
    Source: "App 8",
    Amount: 175.0,
    Status: "Active",
    UserId: 1234,
    Joined: "August",
    Group: "Tech",
  },
  {
    Source: "App 9",
    Amount: 400.0,
    Status: "Pending",
    UserId: 5678,
    Joined: "September",
    Group: "Finance",
  },
  {
    Source: "App 10",
    Amount: 225.0,
    Status: "Active",
    UserId: 9012,
    Joined: "October",
    Group: "Marketing",
  },
  {
    Source: "App 11",
    Amount: 275.0,
    Status: "Cancelled",
    UserId: 3456,
    Joined: "November",
    Group: "Tech",
  },
  {
    Source: "App 12",
    Amount: 150.0,
    Status: "Active",
    UserId: 7890,
    Joined: "December",
    Group: "Finance",
  },
  {
    Source: "App 13",
    Amount: 350.0,
    Status: "Pending",
    UserId: 2345,
    Joined: "January",
    Group: "Marketing",
  },
  {
    Source: "App 14",
    Amount: 275.0,
    Status: "Cancelled",
    UserId: 6789,
    Joined: "February",
    Group: "Tech",
  },
  {
    Source: "App 15",
    Amount: 125.0,
    Status: "Active",
    UserId: 1234,
    Joined: "March",
    Group: "Finance",
  },
  {
    Source: "App 16",
    Amount: 275.0,
    Status: "Pending",
    UserId: 5678,
    Joined: "April",
    Group: "Marketing",
  },
  {
    Source: "App 17",
    Amount: 200.0,
    Status: "Active",
    UserId: 9012,
    Joined: "May",
    Group: "Tech",
  },
  // Add more rows here
];
